package ceremony

import (
	"fmt"
	"strings"
)

// PersonaScopeAllows exposes the persona scope's allow lists to the
// account-half drivers (the kit renders them, the Synadia driver
// declares them) — one source, so no authored scope can drift from the
// embedded one (spec 010 SC-004).
func PersonaScopeAllows() (pub, sub []string) {
	return append([]string(nil), scopePubAllow...), append([]string(nil), scopeSubAllow...)
}

// Kit renders the self-hosted account half as a document the substrate's
// operator applies (design 0003 §4): exact nsc commands, the server
// config fragments a conversion needs, the push, and the hand-back. No
// placeholders the operator must compute — every value is real. The kit
// carries public keys only; regenerating it is free and byte-identical
// until the account half exists. The command sequence is validated
// against a real nsc (spec 010 SC-004, quickstart.md).
func Kit(s *State, dir string) string {
	realmAcct := "soulstream-" + s.Realm
	authAcct := "soulstream-" + s.Realm + "-auth"
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# The soulstream kit — realm %q on your NATS server", s.Realm)
	w("")
	w("Generated by `soulstream init` for %s; regenerated identically on", s.BYOURL)
	w("every run until the account half exists. Apply it with `nsc` against")
	w("the operator that runs that server. Everything below is a public key:")
	w("the seeds these keys belong to stay in the state directory, and no")
	w("seed crosses this document in either direction (design 0003 §3).")
	w("")
	w("The account names are suggestions; the keys are what soulstream")
	w("verifies. soulstream never authors an account, never pushes a JWT,")
	w("and never edits this server's configuration.")
	w("")
	w("## 1. The two accounts (nsc)")
	w("")
	w("    nsc add account %s", realmAcct)
	w("    nsc edit account %s --js-mem-storage -1 --js-disk-storage -1 --js-streams -1 --js-consumer -1", realmAcct)
	w("    nsc edit account %s --sk %s --sk %s", realmAcct, s.WorkloadSigningPub, s.RealmSigningPub)
	w("    nsc edit signing-key --account %s --sk %s --role soulstream-user \\", realmAcct, s.RealmSigningPub)
	w("      --allow-pub '%s' \\", strings.Join(scopePubAllow, ","))
	w("      --allow-sub '%s'", strings.Join(scopeSubAllow, ","))
	w("    nsc add account %s", authAcct)
	w("    nsc edit account %s --sk %s", authAcct, s.AuthSigningPub)
	w("    nsc edit authcallout --account %s --auth-user %s \\", authAcct, s.IssuerUserPub)
	w("      --allowed-account $(nsc describe account %s --field sub | tr -d '\"') \\", realmAcct)
	w("      --curve %s", s.CalloutPub)
	w("")
	w("The JetStream limits above are unlimited; bound them if that is not")
	w("what this server offers — the realm needs enough for its stream,")
	w("object store, and buckets. The first key on %s stays PLAIN", realmAcct)
	w("(no role): it mints workload users whose permissions ride in their")
	w("own JWTs, and a scoped key would reject them.")
	w("")
	w("## 2. Server configuration (only when converting to operator mode)")
	w("")
	w("A server already in operator mode needs nothing here. A server still")
	w("on conf-file auth needs the standard operator-mode conversion — these")
	w("fragments, filled from your own nsc store:")
	w("")
	w("    operator: /path/to/operator.jwt        # nsc describe operator --raw")
	w("    system_account: <SYS account public key>")
	w("    resolver { type: full, dir: './jwt' }   # or your resolver of choice")
	w("")
	w("Optional, after founding completes: `default_sentinel` pointed at the")
	w("JWT inside <state>/sentinel.creds lets clients connect with the bare")
	w("token option. Without it, distribute sentinel.creds — it is public by")
	w("design (a deny-all bearer), so it needs no custody.")
	w("")
	w("## 3. Push, then hand back the two account keys")
	w("")
	w("    nsc push -A")
	w("    soulstream init --state %s \\", dir)
	w("      --auth-account $(nsc describe account %s --field sub | tr -d '\"') \\", authAcct)
	w("      --realm-account $(nsc describe account %s --field sub | tr -d '\"')", realmAcct)
	w("")
	w("That re-run verifies the substrate behaviourally and performs the")
	w("wire half (buckets, vault imports, your one access token, the")
	w("sentinel). Anything not applied above is refused by name.")
	return b.String()
}
